[package]
name = "abacas-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
abacas.workspace = true
rug.workspace = true
rustyline = { version = "17.0.2", features = ["derive"] }
syntect = "5.3.0"
